### ISSUE TITLE
Strategy succeeds even if user is not found

### ISSUE THREAD

**Issue by Metamist** [feathersjs/authentication-jwt#27]
If a user signs in and the server later removes the user from the database while the JWT is still valid, the strategy will attempt to find the user. If it does not find it, the strategy still succeeds.
~~There is a missing existance check at [verifier.js:30](https://github.com/feathersjs/feathers-authentication-jwt/blob/master/src/verifier.js#L30).~~

~~If there is no user found, the strategy should fail. Likewise, if the user lookup/population fails for another reason, the strategy should *also* fail, as indicated at [verifier.js:36](https://github.com/feathersjs/feathers-authentication-jwt/blob/master/src/verifier.js#L36)~~

*Edit:* The only thing that needs to change is [verifier.js:36](https://github.com/feathersjs/feathers-authentication-jwt/blob/master/src/verifier.js#L36) which should return `done(error)` rather than `done(null, {}, payload)`.

```
feathers-authentication-jwt:verify Looking up user by id 5606d82e-69bc-49fc-8d14-1456a8776ec9 +2ms
feathers-errors NotFound(404): No record found for id '5606d82e-69bc-49fc-8d14-1456a8776ec9' +198ms
feathers-errors {} +1ms
info: error: users - Method: get: No record found for id '5606d82e-69bc-49fc-8d14-1456a8776ec9'
error:  Error
    at Object.<anonymous> (E:\Development\FeathersJS\meta-drm\node_modules\feathers-errors\lib\index.js:70:27)
    at Module._compile (module.js:571:32)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (E:\Development\FeathersJS\meta-drm\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (E:\Development\FeathersJS\meta-drm\node_modules\feathers-rest\lib\wrappers.js:13:23)
feathers-authentication-jwt:verify Error populating user with id 5606d82e-69bc-49fc-8d14-1456a8776ec9 { Error
    at Object.<anonymous> (E:\Development\FeathersJS\meta-drm\node_modules\feathers-errors\lib\index.js:70:27)
    at Module._compile (module.js:571:32)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (E:\Development\FeathersJS\meta-drm\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (E:\Development\FeathersJS\meta-drm\node_modules\feathers-rest\lib\wrappers.js:13:23)
  type: 'FeathersError',
  name: 'NotFound',
  message: 'No record found for id \'5606d82e-69bc-49fc-8d14-1456a8776ec9\'',
  code: 404,
  className: 'not-found',
  data: undefined,
  errors: {} } +6ms
feathers-authentication:passport:authenticate 'jwt' authentication strategy succeeded {} { userId: '5606d82e-69bc-49fc-8d14-1456a8776ec9',
  iat: 1499935648,
  exp: 1500022048,
  aud: 'https://yourdomain.com',
  iss: 'feathers',
  sub: 'anonymous' } +5ms
```
This issue leads to my users still being signed in even after their user is deleted, the only difference is that their `user` object is undefined.

**Comment by ekryski** [comment]
This is where your permissions checks should come into play or blacklisting/whitelisting tokens. This will get better in the next major version of `feathers-authenticaiton` https://github.com/feathersjs/feathers-authentication/issues/513.

Currently, when your users are deleted their token is effectively now a JWT for an anonymous user. If you're not differentiating between anonymous users and regular users then you have 3 options:

1. Add permissions checks in hooks to differentiate access
2. [Customize the `Verifier`](https://github.com/feathersjs/feathers-authentication-jwt#customizing-the-verifier) to reject if the user isn't populated. Similar to your PR.
3. Implement an access token white list or black list and check against when users authenticate, and update the list when users are deleted or their access is revoked.

**Comment by ekryski** [comment]
Related to #14. Would be better to have a least more visibility into when a user is not populated.
